/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bfs;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.LinkedList;

public class Tests {
    LinkedList<LinkedList<Integer>> grafo;
    int tamanho_grafo = 7;

    @BeforeEach
    public void criarGrafo() {
        this.grafo = new LinkedList<>();
        for (int i = 0; i < this.tamanho_grafo; i++) {
            this.grafo.add(new LinkedList<Integer>());
        }

        grafo.get(1).add(2);
        grafo.get(1).add(5);

        grafo.get(2).add(1);
        grafo.get(2).add(3);
        grafo.get(2).add(5);

        grafo.get(3).add(2);
        grafo.get(3).add(4);

        grafo.get(4).add(3);
        grafo.get(4).add(5);
        grafo.get(4).add(6);

        grafo.get(5).add(1);
        grafo.get(5).add(2);
        grafo.get(5).add(4);

        grafo.get(6).add(4);
    }

    @Test
    public void anteDoVertice6() {
        BFS s = new BFS(this.grafo);
        s.BFS_start(2);

        int actual = s.before[6];
        int expected = 4;

        assertEquals(expected, actual);
    }

    @Test
    public void anteDoVertice1() {
        BFS s = new BFS(this.grafo);
        s.BFS_start(2);

        int actual = s.before[1];
        int expected = 2;

        assertEquals(expected, actual);
    }

    @Test
    public void distanciaDoVertice6() {
        BFS s = new BFS(this.grafo);
        s.BFS_start(1);

        int actual = s.level[6];
        int expected = 3;

        assertEquals(expected, actual);
    }

    @Test
    public void corDoVertice0() {
        BFS s = new BFS(this.grafo);
        s.BFS_start(2);

        int actual = s.color[0];
        int expected = -1;

        assertEquals(expected, actual);
    }
}
